language: java

env:
  global:
    - CC_TEST_REPORTER_ID=CODECLIMATE_REPORTER_ID

jdk:
  - oraclejdk8
  - oraclejdk9

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn clean cobertura:cobertura
  - ./cc-test-reporter format-coverage --debug --input-type 'cobertura' --output "coverage/codeclimate.$N.json" --prefix /home/travis/build/itarverne/qrcodify/target/surefire-reports
  - ./cc-test-reporter sum-coverage --output coverage/codeclimate.*.json 
  - ./cc-test-reporter upload-coverage

script:
  - mkdir test
  - mvn clean test -Dpath="test" -B

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
